import { Menu } from '@/components'
import '@/styles/global.css'
import '@/styles/normalize.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Montar en Monociclo',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Menu />
				<div>{children}</div>
			</body>
		</html>
	)
}
